/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import com.oracle.peoplesoft.bass2.qe.utility.Constants;
import com.oracle.peoplesoft.bass2.qe.utility.Utils;

import static org.junit.Assert.*;

import org.junit.Ignore;

public class LibraryTest {
    @Test 
    @Ignore
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test
    public void testCase001() {
    	assertEquals(Constants.URL,"wwww");
    }
    
    @Test 
    public void TestCase002() {
    	assertNotNull(Utils.openBrowser(Constants.URL));
    }
    @Test
    public void Login() {
    	
    }
}
